### ISSUE TITLE
JSON error retriving data

### ISSUE THREAD

**Issue by Spheres-cu** [ibnuh/Flow.Launcher.Plugin.IPDetails#2]
The JSON value could not be converted to System.Boolean. Path: $.is_crawler | LineNumber: 5 | BytePositionInLine: 27.

**Comment by ibnuh** [comment]
Could you provide the json output when you visit [https://api.ipapi.is/](https://api.ipapi.is/), you can redact the IP address

**Comment by Spheres-cu** [comment]
> Could you provide the json output when you visit https://api.ipapi.is/, you can redact the IP address

It seems that it was a connection problem, also at that time I did not have the KEY API, now the searches that gave me the error are reflected in the ipapi_cache.json without problems. Thank you!
